export const parcel_fields_from_regrid = [
  { field: 'ogc_fid', label: 'Object ID' },
  { field: 'geoid',  label: 'FIPS Code' },
  { field: 'parcelnumb',  label: 'Parcel ID' },
  { field: 'address',  label: 'Parcel Address' },
  { field: 'scity',  label: 'Parcel Address City' },
  { field: 'county',  label: 'Parcel Address County' },
  { field: 'state2',  label: 'Parcel Address State' },
  { field: 'szip5',  label: '5 Digit Parcel Zip Code' },
  { field: 'szip',  label: 'Parcel Address Zip Code' },
  { field: 'address2',  label: 'Parcel Address Second Line' },
  { field: 'owner',  label: 'Owner Name' },
  { field: 'owntype',  label: 'Owner Type' },
  { field: 'ownfrst',  label: 'Owner First Name' },
  { field: 'ownlast',  label: 'Owner Last Name' },
  { field: 'owner2',  label: 'Second Owner Name' },
  { field: 'owner3',  label: 'Third Owner Name' },
  { field: 'owner4',  label: 'Fourth Owner Name' },
  { field: 'previous_owner',  label: 'Previous Owner Name' },
  // { field: 'parcelnumb_no_formatting',  label: 'Parcel ID without Formatting' },
  { field: 'saleprice',  label: 'Last Sale Price ($)' },
  { field: 'saledate',  label: 'Last Sale Date' },
  { field: 'parvaltype',  label: 'Parcel Value Type' },
  { field: 'parval',  label: 'Total Parcel Value ($)' },
  { field: 'improvval',  label: 'Improvement Value ($)' },
  { field: 'landval',  label: 'Land Value ($)' },
  { field: 'lat',  label: 'Latitude' },
  { field: 'lon',  label: 'Longitude' },
  { field: 'taxamt',  label: 'Annual Tax Bill' },
  { field: 'taxyear',  label: 'Tax Year' },
  { field: 'usecode',  label: 'Parcel Use Code' },
  { field: 'usedesc',  label: 'Parcel Use Description' },
  { field: 'zoning',  label: 'Zoning Code' },
  { field: 'zoning_description',  label: 'Zoning Description' },
  { field: 'zoning_type',  label: 'Zoning Type' },
  { field: 'zoning_subtype',  label: 'Zoning Subtype' },
  { field: 'zoning_code_link',  label: 'Zoning Code Link' },
  { field: 'zoning_id',  label: 'Zoning Area ID' },
  { field: 'struct',  label: 'Structure on Parcel' },
  { field: 'structno',  label: 'Number of Structures on Parcel' },
  { field: 'yearbuilt',  label: 'Structure Year Built' },
  { field: 'numstories',  label: 'Number of Stories' },
  { field: 'numunits',  label: 'Number of Living Units' },
  { field: 'numrooms',  label: 'Number of Rooms' },
  { field: 'structstyle',  label: 'Structure Style' },
  { field: 'agval',  label: 'Agricultural Value' },
  { field: 'homestead_exemption',  label: 'Homestead Exemption' },
  { field: 'state_parcelnumb',  label: 'State Provided Parcel ID Number' },
  { field: 'account_number',  label: 'Parcel Account Number' },
  { field: 'tax_id',  label: 'Parcel Tax Identification Number' },
  { field: 'alt_parcelnumb1',  label: 'First Alternative Parcel ID' },
  { field: 'alt_parcelnumb2',  label: 'Second Alternative Parcel ID' },
  { field: 'alt_parcelnumb3',  label: 'Third Alternative Parcel ID' },
  { field: 'mailadd',  label: 'Mailing Address' },
  { field: 'mail_city',  label: 'Mailing Address City' },
  { field: 'mail_country',  label: 'Mailing Address Country' },
  { field: 'mail_state2',  label: 'Mailing Address State' },
  { field: 'mail_address2',  label: 'Mailing Address Second Line' },
  { field: 'careof',  label: 'Mailing Address Care Of' },
  { field: 'mail_addno',  label: 'Mailing Address Street Number' },
  { field: 'mail_addpref',  label: 'Mailing Address Street Prefix' },
  { field: 'mail_addstr',  label: 'Mailing Address Street Name' },
  { field: 'mail_addsttyp',  label: 'Mailing Address Street Type' },
  { field: 'mail_addstsuf',  label: 'Mailing Address Street Suffix' },
  { field: 'mail_unit',  label: 'Mailing Address Unit Number' },
  { field: 'mail_zip',  label: 'Mailing Address ZIP Code' },
  // { field: 'mail_urbanization',  label: 'Mailing Address Urbanizacion (Puerto Rico)' },
  // { field: 'saddno',  label: 'Parcel Address Number' },
  { field: 'saddpref',  label: 'Parcel Address Prefix' },
  { field: 'saddstr',  label: 'Parcel Address Street Name' },
  { field: 'saddsttyp',  label: 'Parcel Address Street Type' },
  { field: 'saddstsuf',  label: 'Parcel Address Street Suffix' },
  { field: 'sunit',  label: 'Parcel Address Unit' },
  // { field: 'original_address',  label: 'Original Parcel Address' },
  { field: 'city',  label: 'US Census County Subdivision' },
  // { field: 'urbanization',  label: 'Parcel Urbanizacion' },
  { field: 'll_address_count',  label: 'Regrid Calculated Total Address Count' },
  { field: 'location_name',  label: 'Location Name' },
  { field: 'address_source',  label: 'Primary Address Source' },
  { field: 'legaldesc',  label: 'Legal Description' },
  { field: 'plat',  label: 'Plat' },
  { field: 'book',  label: 'Book' },
  { field: 'page',  label: 'Page' },
  { field: 'block',  label: 'Block' },
  { field: 'lot',  label: 'Lot' },
  { field: 'neighborhood',  label: 'Neighborhood' },
  { field: 'subdivision',  label: 'Subdivision' },
  { field: 'fema_flood_zone',  label: 'FEMA Flood Zone' },
  { field: 'fema_flood_zone_subtype',  label: 'FEMA Flood Zone Subtype' },
  { field: 'fema_flood_zone_raw',  label: 'FEMA Flood Zone Raw Data' },
  { field: 'fema_flood_zone_data_date',  label: 'FEMA Flood Zone Data Date' },
  { field: 'qoz',  label: '	Federal Qualified Opportunity Zone' },
  { field: 'qoz_tract',  label: 'Qualified Opportunity Zone Tract Number' },
  { field: 'census_tract',  label: 'Census 2020 Tract' },
  { field: 'census_block',  label: 'Census 2020 Block' },
  { field: 'census_blockgroup',  label: 'Census 2020 Blockgroup' },
  { field: 'census_zcta',  label: 'Census Zip Code Tabulation Area' },
  { field: 'census_elementary_school_district',  label: 'Census Provided Elementary School District' },
  { field: 'census_secondary_school_district',  label: 'Census Provided Secondary School District' },
  { field: 'census_unified_school_district',  label: 'Census Provided Unified School District' },
  { field: 'll_last_refresh',  label: 'Last County Refresh Date' },
  { field: 'sourceurl',  label: 'Source URL' },
  { field: 'recrdareatx',  label: 'Recorded Area (text)' },
  { field: 'recrdareano',  label: 'Total Square Footage of Structures' },
  { field: 'gisacre',  label: 'County-Provided Acres' },
  { field: 'sqft',  label: 'County-Provided Parcel Square Feet' },
  { field: 'll_gisacre',  label: 'Regrid Calculated Parcel Acres' },
  { field: 'll_gissqft',  label: 'Regrid Calculated Parcel Square Feet' },
  { field: 'll_bldg_footprint_sqft',  label: 'Regrid Calculated Building Footprint Square Feet' },
  { field: 'll_bldg_count',  label: 'Regrid Calculated Building Count' },
  { field: 'cdl_raw',  label: 'Cropland Data Layer Raw Values' },
  { field: 'cdl_majority_category',  label: 'Cropland Data Layer Majority Category' },
  { field: 'cdl_majority_percent',  label: 'Cropland Data Layer Majority Percent' },
  { field: 'cdl_date',  label: 'Cropland Data Layer Date' },
  { field: 'plss_township',  label: 'PLSS Township' },
  { field: 'plss_section',  label: 'PLSS Section' },
  { field: 'plss_range',  label: 'PLSS Range' },
  { field: 'reviseddate',  label: 'Date of Last Revision' },
  { field: 'path',  label: 'Parcel Path' },
  { field: 'll_stable_id',  label: 'Stable ID Status' },
  { field: 'll_uuid',  label: 'Regrid UUID' },
  { field: 'll_stack_uuid',  label: 'Parcel Stack UUID' },
  { field: 'll_row_parcel',  label: 'Regrid Right-of-Way Parcel Flag' },
  { field: 'll_updated_at',  label: 'Last Modified' },
  { field: 'placekey',  label: 'Placekey' },
  { field: 'dpv_status',  label: 'USPS Delivery Point Validation' },
  { field: 'dpv_codes',  label: 'Delivery Point Validation Codes' },
  { field: 'dpv_notes',  label: 'Delivery Point Validation Notes' },
  { field: 'dpv_type',  label: 'Delivery Point Match Type' },
  { field: 'cass_errorno',  label: 'CASS Error Codes' },
  { field: 'rdi',  label: 'Residential Delivery Indicator' },
  { field: 'usps_vacancy',  label: 'USPS Vacancy Indicator' },
  { field: 'usps_vacancy_date',  label: 'USPS Vacancy Indicator Date' },
  { field: 'padus_public_access',  label: 'PAD-US Public Access Designation' },
  { field: 'lbcs_activity',  label: 'Land Use Code: Activity' },
  { field: 'lbcs_activity_desc',  label: 'Land Use Code Description: Activity' },
  { field: 'lbcs_function',  label: 'Land Use Code: Function' },
  { field: 'lbcs_function_desc',  label: 'Land Use Code Description: Function' },
  { field: 'lbcs_structure',  label: 'Land Use Code: Structure' },
  { field: 'lbcs_structure_desc',  label: 'Land Use Code Description: Structure' },
  { field: 'lbcs_site',  label: 'Land Use Code: Site' },
  { field: 'lbcs_site_desc',  label: 'Land Use Code Description: Site' },
  { field: 'lbcs_ownership',  label: 'Land Use Code: Ownership' },
  { field: 'lbcs_ownership_desc',  label: 'Land Use Code Description: Ownership' },
]